server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    url: jdbc:mysql://localhost:3306/month5?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: root

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka,http://eureka7002.com:7002/eureka #集群版
      #defaultZone: http://localhost:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2


#eureka:
#  client:
#    register-with-eureka: true
#    fetchRegistry: true
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
#  instance:
#    instance-id: payment8001
#    prefer-ip-address: true



mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.mr.springcloud.entities

