server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #动态路由
          predicates:
              - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE #动态路由
          predicates:
            - Path=/payment/feign/**   #断言,路径相匹配的进行路由

        - id: payment_route3
          uri: lb://CLOUD-PAYMENT-SERVICE #动态路由
          predicates:
            - Path=/payment/lb
            - After=2020-08-24T10:59:34.102+08:00[Asia/Shanghai]
            #- Cookie=username,t
            #- Header=X-Request-Id, \d+
            #- Host=**.mr.com
            - Method=GET
           # - Query=username, \d+ #要有参数名称并且是正整数才能路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7002.com:7002/eureka

