
eureka:
  client:
    register-with-eureka: true   #表识不向注册中心注册自己
    fetch-registry: true  #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/

spring:
  application:
    name: cloud-provider-hystrix-order
  main:
    allow-bean-definition-overriding: true
server:
  port: 80


